// <auto-generated by SyncToolCount.ps1 - do not edit by hand>
namespace RevitAIConnector
{
    internal static class McpToolCount
    {
        /// <summary>Must equal server.tool count in McpServer/src/index.ts and /api routes in RevitRequestHandler.</summary>
        public const int Value = 252;
    }
}
