# Ensures Revit API route count matches MCP server.tool registrations; writes McpToolCount.g.cs
$ErrorActionPreference = "Stop"
$here = $PSScriptRoot
$handler = Join-Path $here "RevitRequestHandler.cs"
$mcpTs = [IO.Path]::GetFullPath((Join-Path $here "..\..\McpServer\src\index.ts"))

if (-not (Test-Path $handler)) { throw "Missing $handler" }
if (-not (Test-Path $mcpTs)) { throw "Missing $mcpTs (expected repo layout RevitAddin/RevitAIConnector -> McpServer)" }

$api = ([regex]::Matches([IO.File]::ReadAllText($handler), 'case "/api/')).Count
$mcp = ([regex]::Matches([IO.File]::ReadAllText($mcpTs), 'server\.tool\(')).Count

if ($api -ne $mcp) {
  throw "Route/tool mismatch: RevitRequestHandler has $api 'case /api/*' but index.ts has $mcp server.tool() calls. Fix before shipping."
}

$outPath = Join-Path $here "McpToolCount.g.cs"
$content = @"
// <auto-generated by SyncToolCount.ps1 - do not edit by hand>
namespace RevitAIConnector
{
    internal static class McpToolCount
    {
        /// <summary>Must equal server.tool count in McpServer/src/index.ts and /api routes in RevitRequestHandler.</summary>
        public const int Value = $api;
    }
}
"@
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($outPath, $content.TrimStart() + "`n", $utf8NoBom)
Write-Host "McpToolCount.g.cs -> $api (API and MCP counts match)."
